import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import AOSInit from "@/components/AosInit";



const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Maõs que ajudam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
    >
      <body className={`${poppins.className} h-full antialiased min-h-full flex flex-col`}>
        <AOSInit/>
        {children}
      </body>
    </html>
  );
}
